# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ec2id < Formula
  desc ""
  homepage ""
  version "0.2.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/thaim/ec2id/releases/download/v0.2.1/ec2id_Darwin_arm64.tar.gz"
      sha256 "5d89846a8bc1e8bdc633ce8d0298ebc668793b6d094e1a892dcc0f580bf1f4ba"

      def install
        bin.install "ec2id"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/thaim/ec2id/releases/download/v0.2.1/ec2id_Darwin_x86_64.tar.gz"
      sha256 "d84c9197f8c44656d157a7857315ff0fe942811a1ed4270a63c409c42eef7f3f"

      def install
        bin.install "ec2id"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/thaim/ec2id/releases/download/v0.2.1/ec2id_Linux_x86_64.tar.gz"
      sha256 "60cf887f7dc22e898d23a55a986d3c7212750507b49524c826a379ea54c74e1d"

      def install
        bin.install "ec2id"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thaim/ec2id/releases/download/v0.2.1/ec2id_Linux_arm64.tar.gz"
      sha256 "6fde4a16311d8111f9938c6bbdb083aa83cefea8d1530ee379451078d2561789"

      def install
        bin.install "ec2id"
      end
    end
  end
end
