# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfcvars < Formula
  desc "tfcvars is a CLI tool that synchronizes variables managed in Terraform Cloud with local variable files"
  homepage "https://github.com/thaim/tfcvars"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/thaim/tfcvars/releases/download/v0.2.0/tfcvars_Darwin_arm64.tar.gz"
      sha256 "b88a55845f035cfee4eb1043d7fbd89cc0ae04acb696af016acc9bb13a788c9a"

      def install
        bin.install "tfcvars"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/thaim/tfcvars/releases/download/v0.2.0/tfcvars_Darwin_x86_64.tar.gz"
      sha256 "69e5931b7a5fb666bfbc3d422e0ecbf7249c609d8a81e708065e85047add82ca"

      def install
        bin.install "tfcvars"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/thaim/tfcvars/releases/download/v0.2.0/tfcvars_Linux_x86_64.tar.gz"
      sha256 "63af412fbd5b56e514076ef12d60772a3134cd35408189e785a946bae4562742"

      def install
        bin.install "tfcvars"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thaim/tfcvars/releases/download/v0.2.0/tfcvars_Linux_arm64.tar.gz"
      sha256 "7422eaa9da16448f25ef31b37b85d61d88ef4d9c065a1caffb2ed637d9ed30d1"

      def install
        bin.install "tfcvars"
      end
    end
  end
end
